# Generated by Django 2.0.5 on 2018-11-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181106_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slastatus',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
