# Generated by Django 2.0.5 on 2018-11-06 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VMs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='slastatus',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slastatus',
            name='vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.VMs'),
        ),
        migrations.AddField(
            model_name='uservms',
            name='vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.VMs'),
        ),
    ]
